//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace SLSShippingApp.RptClasses
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/clsPackingLabels.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/clsPackingLabels.xsd", IsNullable = false)]
    public partial class clsPackingLabels
    {

        private clsPackingLabelsTblTickets[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tblTickets")]
        public clsPackingLabelsTblTickets[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/clsPackingLabels.xsd")]
    public partial class clsPackingLabelsTblTickets
    {

        private string orderOrSONumberField;

        private string ptField;

        private string pickingTicketField;

        private System.DateTime pickedDateField;

        private bool pickedDateFieldSpecified;

        private string customerNumberField;

        private string customerNameField;

        private string pONumberField;

        private string shipViaDescriptionField;

        private int boxCountField;

        private bool boxCountFieldSpecified;

        private string operatorNameField;

        private int numberOfBoxesField;

        private bool numberOfBoxesFieldSpecified;

        private string environUserField;

        /// <remarks/>
        public string OrderOrSONumber
        {
            get
            {
                return this.orderOrSONumberField;
            }
            set
            {
                this.orderOrSONumberField = value;
            }
        }

        /// <remarks/>
        public string PT
        {
            get
            {
                return this.ptField;
            }
            set
            {
                this.ptField = value;
            }
        }

        /// <remarks/>
        public string PickingTicket
        {
            get
            {
                return this.pickingTicketField;
            }
            set
            {
                this.pickingTicketField = value;
            }
        }

        /// <remarks/>
        public System.DateTime PickedDate
        {
            get
            {
                return this.pickedDateField;
            }
            set
            {
                this.pickedDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PickedDateSpecified
        {
            get
            {
                return this.pickedDateFieldSpecified;
            }
            set
            {
                this.pickedDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string CustomerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
            }
        }

        /// <remarks/>
        public string CustomerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        public string PONumber
        {
            get
            {
                return this.pONumberField;
            }
            set
            {
                this.pONumberField = value;
            }
        }

        /// <remarks/>
        public string ShipViaDescription
        {
            get
            {
                return this.shipViaDescriptionField;
            }
            set
            {
                this.shipViaDescriptionField = value;
            }
        }

        /// <remarks/>
        public int BoxCount
        {
            get
            {
                return this.boxCountField;
            }
            set
            {
                this.boxCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoxCountSpecified
        {
            get
            {
                return this.boxCountFieldSpecified;
            }
            set
            {
                this.boxCountFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string OperatorName
        {
            get
            {
                return this.operatorNameField;
            }
            set
            {
                this.operatorNameField = value;
            }
        }

        /// <remarks/>
        public int NumberOfBoxes
        {
            get
            {
                return this.numberOfBoxesField;
            }
            set
            {
                this.numberOfBoxesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfBoxesSpecified
        {
            get
            {
                return this.numberOfBoxesFieldSpecified;
            }
            set
            {
                this.numberOfBoxesFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string EnvironUser
        {
            get
            {
                return this.environUserField;
            }
            set
            {
                this.environUserField = value;
            }
        }
    }
}