//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Reflection;
using System.Collections.Generic;
using System.Collections;
using System.Windows.Forms;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace SLSShippingApp.RptClasses 
{

    /// <remarks/>


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/clsPrintLabel.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/clsPrintLabel.xsd", IsNullable = false)]
    public partial class clsPrintLabel : BindingSource //IEnumerable<KeyValuePair<string, string>>
    {
        

       
    //    private clsPrintLabelTblLabel[] itemsField;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("tblLabel")]
    //    public clsPrintLabelTblLabel[] Items
    //    {
    //        get
    //        {
    //            return this.itemsField;
    //        }
    //        set
    //        {
    //            this.itemsField = value;
    //        }
    //    }
    //    public IEnumerator<KeyValuePair<string, string>> GetEnumerator()
    //    {
    //        yield return new KeyValuePair<string,string>(Items.GetValue(0,0).ToString(),Items.GetValue(0,0).ToString());
    //        yield return new KeyValuePair<string, string>(Items.GetValue(1, 1).ToString(), Items.GetValue(1, 1).ToString());
    //        yield return new KeyValuePair<string, string>(Items.GetValue(2, 2).ToString(), Items.GetValue(2, 2).ToString());
    //        yield return new KeyValuePair<string, string>(Items.GetValue(3, 3).ToString(), Items.GetValue(3, 3).ToString());
    //        yield return new KeyValuePair<string, string>(Items.GetValue(4, 4).ToString(), Items.GetValue(4, 4).ToString());
    //        yield return new KeyValuePair<string, string>(Items.GetValue(5, 5).ToString(), Items.GetValue(5, 5).ToString());
    //        yield return new KeyValuePair<string, string>(Items.GetValue(6, 6).ToString(), Items.GetValue(6, 6).ToString());
    //        yield return new KeyValuePair<string, string>(Items.GetValue(7, 7).ToString(), Items.GetValue(7, 7).ToString());
    //        yield return new KeyValuePair<string, string>(Items.GetValue(8, 8).ToString(), Items.GetValue(8, 8).ToString());
    //        yield return new KeyValuePair<string, string>(Items.GetValue(9, 9).ToString(), Items.GetValue(9, 9).ToString());
    //        yield return new KeyValuePair<string, string>(Items.GetValue(10, 10).ToString(), Items.GetValue(10, 10).ToString());
    //    }
    //    IEnumerator IEnumerable.GetEnumerator()
    //    {
    //        return GetEnumerator();
    //    }
    //}

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/clsPrintLabel.xsd")]
    //public partial class clsPrintLabelTblLabel : IEnumerable<KeyValuePair<string,string>> 
    //{

        private string orderNumberField;

        private System.DateTime shippingDateField;

        private bool shippingDateFieldSpecified;

        private string stockNumberField;

        private string bayLocationField;

        private int orderSizeField;

        private bool orderSizeFieldSpecified;

        private string bayLocationOnlyField;

        private string customerNumField;

        private string customerNameField;

        private bool isKitField;

        private bool isKitFieldSpecified;

        private string itemDesc1Field;

        private string itemDesc2Field;

        private string componentItemNumberField;

        private string operatorNameField;

        private string environUserField;

        private decimal orderWeightField;

        private bool orderWeightFieldSpecified;

        private string imageField;

        /// <remarks/>
        public string OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ShippingDate
        {
            get
            {
                return this.shippingDateField;
            }
            set
            {
                this.shippingDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShippingDateSpecified
        {
            get
            {
                return this.shippingDateFieldSpecified;
            }
            set
            {
                this.shippingDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string StockNumber
        {
            get
            {
                return this.stockNumberField;
            }
            set
            {
                this.stockNumberField = value;
            }
        }

        /// <remarks/>
        public string BayLocation
        {
            get
            {
                return this.bayLocationField;
            }
            set
            {
                this.bayLocationField = value;
            }
        }

        /// <remarks/>
        public int OrderSize
        {
            get
            {
                return this.orderSizeField;
            }
            set
            {
                this.orderSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderSizeSpecified
        {
            get
            {
                return this.orderSizeFieldSpecified;
            }
            set
            {
                this.orderSizeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string BayLocationOnly
        {
            get
            {
                return this.bayLocationOnlyField;
            }
            set
            {
                this.bayLocationOnlyField = value;
            }
        }

        /// <remarks/>
        public string CustomerNum
        {
            get
            {
                return this.customerNumField;
            }
            set
            {
                this.customerNumField = value;
            }
        }

        /// <remarks/>
        public string CustomerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        public bool IsKit
        {
            get
            {
                return this.isKitField;
            }
            set
            {
                this.isKitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsKitSpecified
        {
            get
            {
                return this.isKitFieldSpecified;
            }
            set
            {
                this.isKitFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ItemDesc1
        {
            get
            {
                return this.itemDesc1Field;
            }
            set
            {
                this.itemDesc1Field = value;
            }
        }

        /// <remarks/>
        public string ItemDesc2
        {
            get
            {
                return this.itemDesc2Field;
            }
            set
            {
                this.itemDesc2Field = value;
            }
        }

        /// <remarks/>
        public string ComponentItemNumber
        {
            get
            {
                return this.componentItemNumberField;
            }
            set
            {
                this.componentItemNumberField = value;
            }
        }

        /// <remarks/>
        public string OperatorName
        {
            get
            {
                return this.operatorNameField;
            }
            set
            {
                this.operatorNameField = value;
            }
        }

        /// <remarks/>
        public string EnvironUser
        {
            get
            {
                return this.environUserField;
            }
            set
            {
                this.environUserField = value;
            }
        }

        /// <remarks/>
        public decimal OrderWeight
        {
            get
            {
                return this.orderWeightField;
            }
            set
            {
                this.orderWeightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderWeightSpecified
        {
            get
            {
                return this.orderWeightFieldSpecified;
            }
            set
            {
                this.orderWeightFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        //public IEnumerator<KeyValuePair<string,string>> GetEnumerator()
        //{
        //    yield return new KeyValuePair<string, string>("OrderNumber", OrderNumber);
        //    yield return new KeyValuePair<string, string>("ShippingDate", ShippingDate.ToLongDateString());
        //    yield return new KeyValuePair<string, string>("StockNumber", StockNumber);
        //    yield return new KeyValuePair<string, string>("BayLocation", BayLocation);
        //    yield return new KeyValuePair<string, string>("CustomerNum", CustomerNum);
        //    yield return new KeyValuePair<string, string>("CustomerName", CustomerName);
        //    yield return new KeyValuePair<string, string>("isKit", IsKit.ToString());
        //    yield return new KeyValuePair<string, string>("ItemDesc1", ItemDesc1);
        //    yield return new KeyValuePair<string, string>("ItemDesc2", ItemDesc2);
        //    yield return new KeyValuePair<string, string>("ComponentItemNumber", ComponentItemNumber);
        //    yield return new KeyValuePair<string, string>("OrderWeight", OrderWeight.ToString());
        //}

        //IEnumerator IEnumerable.GetEnumerator()
        //{
        //    return GetEnumerator();
        //}
    }
    public class clsPrintLabelsSource : IEnumerable<clsPrintLabel>
    {
        private ICollection<clsPrintLabel> list;
        //public clsPrintLabelsSource(IEnumerable<clsPrintLabel> data)
        //{
        //    list = data.ToList();
        //}
        public IEnumerator<clsPrintLabel> GetEnumerator()
        {
            foreach(var item in list)
            {
                yield return item;
            }
        }
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return ((IEnumerable < clsPrintLabel >) this).GetEnumerator();
        }
    }
}
