//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace SLSShippingApp.RptClasses
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/clsQuickShipLabel.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/clsQuickShipLabel.xsd", IsNullable = false)]
    public partial class clsQuickShipLabel
    {

        private clsQuickShipLabelTblLabelQuickShip[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tblLabelQuickShip")]
        public clsQuickShipLabelTblLabelQuickShip[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/clsQuickShipLabel.xsd")]
    public partial class clsQuickShipLabelTblLabelQuickShip
    {

        private string stockNumberField;

        private string poField;

        private string operatorField;

        private string environUserField;

        private string txtImageFileField;

        /// <remarks/>
        public string StockNumber
        {
            get
            {
                return this.stockNumberField;
            }
            set
            {
                this.stockNumberField = value;
            }
        }

        /// <remarks/>
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }

        /// <remarks/>
        public string EnvironUser
        {
            get
            {
                return this.environUserField;
            }
            set
            {
                this.environUserField = value;
            }
        }

        /// <remarks/>
        public string txtImageFile
        {
            get
            {
                return this.txtImageFileField;
            }
            set
            {
                this.txtImageFileField = value;
            }
        }
    }
}