//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DS_rptPrintLabel.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DS_rptPrintLabel.xsd", IsNullable=false)]
public partial class DS_rptPrintLabel {
    
    private DS_rptPrintLabelTblLabel[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tblLabel")]
    public DS_rptPrintLabelTblLabel[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DS_rptPrintLabel.xsd")]
public partial class DS_rptPrintLabelTblLabel {
    
    private string orderNumberField;
    
    private System.DateTime shippingDateField;
    
    private bool shippingDateFieldSpecified;
    
    private string stockNumberField;
    
    private string bayLocationField;
    
    private int orderSizeField;
    
    private bool orderSizeFieldSpecified;
    
    private string bayLocationOnlyField;
    
    private string customerNumField;
    
    private string customerNameField;
    
    private bool isKitField;
    
    private bool isKitFieldSpecified;
    
    private string itemDesc1Field;
    
    private string itemDesc2Field;
    
    private string componentItemNumberField;
    
    private string operatorNameField;
    
    private string environUserField;
    
    private decimal orderWeightField;
    
    private bool orderWeightFieldSpecified;
    
    private string imageField;
    
    /// <remarks/>
    public string OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ShippingDate {
        get {
            return this.shippingDateField;
        }
        set {
            this.shippingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShippingDateSpecified {
        get {
            return this.shippingDateFieldSpecified;
        }
        set {
            this.shippingDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string StockNumber {
        get {
            return this.stockNumberField;
        }
        set {
            this.stockNumberField = value;
        }
    }
    
    /// <remarks/>
    public string BayLocation {
        get {
            return this.bayLocationField;
        }
        set {
            this.bayLocationField = value;
        }
    }
    
    /// <remarks/>
    public int OrderSize {
        get {
            return this.orderSizeField;
        }
        set {
            this.orderSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrderSizeSpecified {
        get {
            return this.orderSizeFieldSpecified;
        }
        set {
            this.orderSizeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string BayLocationOnly {
        get {
            return this.bayLocationOnlyField;
        }
        set {
            this.bayLocationOnlyField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerNum {
        get {
            return this.customerNumField;
        }
        set {
            this.customerNumField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    public bool IsKit {
        get {
            return this.isKitField;
        }
        set {
            this.isKitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsKitSpecified {
        get {
            return this.isKitFieldSpecified;
        }
        set {
            this.isKitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ItemDesc1 {
        get {
            return this.itemDesc1Field;
        }
        set {
            this.itemDesc1Field = value;
        }
    }
    
    /// <remarks/>
    public string ItemDesc2 {
        get {
            return this.itemDesc2Field;
        }
        set {
            this.itemDesc2Field = value;
        }
    }
    
    /// <remarks/>
    public string ComponentItemNumber {
        get {
            return this.componentItemNumberField;
        }
        set {
            this.componentItemNumberField = value;
        }
    }
    
    /// <remarks/>
    public string OperatorName {
        get {
            return this.operatorNameField;
        }
        set {
            this.operatorNameField = value;
        }
    }
    
    /// <remarks/>
    public string EnvironUser {
        get {
            return this.environUserField;
        }
        set {
            this.environUserField = value;
        }
    }
    
    /// <remarks/>
    public decimal OrderWeight {
        get {
            return this.orderWeightField;
        }
        set {
            this.orderWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrderWeightSpecified {
        get {
            return this.orderWeightFieldSpecified;
        }
        set {
            this.orderWeightFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
}
